### ISSUE TITLE
PR 본문 구성

### ISSUE THREAD

**Issue by joonparkhere** [joonparkhere/algorithm-study#16]
현재 PR 을 보낼 때 본문에
- 대략적인 풀이
- 소요 메모리와 시간

두 가지 항목을 포함하고 있습니다.

여기서 대략적인 풀이의 내용이 코드 레벨에서의 설명보다는
본인이 처음 문제를 보고 코드를 작성하기 전, 생각의 흐름을 적는 게 어떨까요?

코드 레벨의 설명을 적어 놓으면 설명과 코드를 번갈아 볼 수밖에 없는 것 같습니다.
이는 이전 방식인 코드에 주석을 다는 것과 별반 다르지 않습니다.

만약 코드 레벨의 설명이 필요하다면, 구현체에 대한 설명보다는 pseudo code 설명처럼 하는 것이 좋은 것 같습니다.

어떤 방법이 더 낫다고 생각하시나요?

**Comment by HyeonjinChoi** [comment]
확실히 설명과 코드를 번갈아 보는 방식에 불편함이 있는 것 같습니다.

말씀하신대로 '대략적인 풀이' 대신에 '생각의 흐름'을 적음으로써 대략적인 아이디어를 보여주고,
pseudo code로 부족한 코드 설명을 보충한다면 나쁘지 않을 것 같습니다.

**Comment by joonparkhere** [comment]
넵 알겠습니다

앞으로의 PR 에서 반영하면 좋을 것 같습니다.
