### ISSUE TITLE
과제 제출명 규칙 변경

### ISSUE THREAD

**Issue by joonparkhere** [joonparkhere/algorithm-study#28]
과제 (문제 풀이) 파일명을 변경하고자 합니다.

자바로도 알고리즘 문제를 풀어보기 위해 환경 세팅을 하던 중에 현 규칙에 변경이 필요할 거 같아서 이슈를 올립니다.

알고 계시다시피, 자바는 클래스명과 파일명이 일치해야 합니다. 다만 파일명 첫 글자로 숫자가 불가능하고 대문자이어야 하기 때문에 현재 파일명 규칙을 유지한다면 다른 언어 풀이 파일명과 자바 언어 풀이 파일명의 일관성이 깨집니다.

더불어, 사실 파일명에 문제 제목이 한글로 포함되어 있는 점도 그리 적절하지는 않은 것 같아 고치려 합니다.

따라서 `${문제사이트(대문자)}_${문제번호}_${풀이한사람}` 으로 변경하면 어떨까요?
예를 들어 아래의 두 문제를 @joonparkhere 가 풀이했다면,
- 백준 사이트의 1234번 크리스마스 트리 문제
- 리트코드 사이트의 122번 Best Time to Buy and Sell Stock II 문제

아래처럼 파일명을 정하면 될 것 같습니다.

- BOJ_1234_joonparkhere.java
- LEETCODE_122_joonparkhere.go

어떨까요?
그리고 문제사이트 부분을 모두 대문자로 할지, 혹은 첫글자만 대문자로 할지 의견 주시면 감사하겠습니다.

P.S.
이 이슈를 정상적으로 마친 후, 현재 main 브랜치에 올려져 있는 과제 파일명은 제가 고쳐서 PR을 보내겠습니다.
현재 진행 중인 PR 혹은 제출할 PR에는 파일명을 수정해주시기 바랍니다.

**Comment by HyeonjinChoi** [comment]
앞으로 다양한 언어로 과제를 진행하기 위해서 한 번은 짚고 넘어가야할 문제였던 것 같습니다.

자바라는 언어 특성상 파일명에 제약이 생기기 때문에, 파일명의 형식을 말씀하신대로 바꾸는 것은 좋은 의견 같습니다.

문제사이트 이름이 모두 대문자인지 아닌지는 크게 중요한 요소는 아닌 것 같지만,
BOJ 와 같은 약자를 사용하기 때문에 모두 대문자로 통일하는 것을 제안드립니다.

**Comment by joonparkhere** [comment]
넵 그렇게 하겠습니다

지금 진행 중인 PR에서의 과제 파일명을 수정 부탁드립니다!
현재 main 브랜치에 올려져 있는 과제는 제가 수정해서 PR을 날리겠습니다.

**Comment by HyeonjinChoi** [comment]
네 알겠습니다.

말씀하신 형식의 파일명으로 모두 수정하도록 하겠습니다.
